# Uncomment the next line to define a global platform for your project

target 'QuizO2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'RealmSwift'
    pod 'Alamofire', '~> 4.7'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'Alamofire-SwiftyJSON'
  # Pods for QuizO2

end
